Repository woowa-techcamp-2021/deal-12, pull requests merged in 2021-07, with the labels that each got.

#9 [bugfix] 컴포넌트 클래스 렌더링 순서 변경
  client/src/core/Component.ts
Labels: bug

#12 [feature] 채팅 목록 페이지 기본 마크업 구조 작성
  client/src/Components/ChatList/index.ts
  client/src/Components/ChatList/styles.scss
  client/src/Components/Shared/ChatListItem.ts
  client/src/Components/Shared/ChatListItem/index.ts
  client/src/Components/Shared/ChatListItem/styles.scss
  client/src/main.ts
Labels: enhancement

#14 [feature] 채팅 페이지 기본 마크업 구조 및 관련 컴포넌트 작성
  client/src/Components/ChatDetail/index.ts
  client/src/Components/ChatDetail/styles.scss
  client/src/Components/Shared/ChatBar/index.ts
  client/src/Components/Shared/ChatBar/styles.scss
  client/src/Components/Shared/ChatBubble.ts
  client/src/Components/Shared/ChatBubble/index.ts
  client/src/Components/Shared/ChatBubble/styles.scss
  client/src/Components/Shared/InfoProduct.ts
  client/src/Components/Shared/InfoProduct/index.ts
  client/src/Components/Shared/InfoProduct/styles.scss
  client/src/main.ts
Labels: enhancement

#15 [feature] 카테고리 페이지 작성
  client/assets/category.svg
  client/assets/menu.svg
  client/assets/pinmap.svg
  client/assets/user.svg
  client/package.json
  client/src/Components/Category/Category.scss
  client/src/Components/Category/Category.ts
  client/src/Components/Category/index.ts
  client/src/Components/Category/styles.scss
  client/src/Components/Home/Home.scss
  client/src/Components/Home/Home.ts
  client/src/Components/Home/index.ts
  client/src/Components/Home/styles.scss
  client/src/Components/Shared/CategoryListItem/CategoryListItem.ts
  client/src/Components/Shared/CategoryListItem/index.ts
  client/src/Components/Shared/CategoryListItem/styles.scss
  client/src/Components/Shared/Header/Header.ts
  client/src/Components/Shared/Header/index.ts
  client/src/Components/Shared/Header/styles.scss
  client/src/Components/Shared/IconButton/index.ts
  client/webpack.config.js
  client/yarn.lock
Labels: enhancement

#19 [feature] 드랍다운 컴포넌트 클래스 작성
  client/assets/down-xs.svg
  client/src/Components/SalesProductDetail/index.ts
  client/src/Components/SalesProductDetail/styles.scss
  client/src/Components/Shared/Dropdown/index.ts
  client/src/Components/Shared/Dropdown/styles.scss
  client/src/Components/Shared/Status/index.ts
  client/src/Components/Shared/Status/styles.scss
Labels: enhancement

#20 [refactor] 기존 함수형 컴포넌트 모두 클래스형으로 전환
  client/src/Components/ChatDetail/index.ts
  client/src/Components/ChatList/index.ts
  client/src/Components/SalesProductDetail/index.ts
  client/src/Components/Shared/ChatListItem/index.ts
  client/src/Components/Shared/InfoProduct/index.ts
  client/src/Components/Shared/InfoSaler/index.ts
Labels: refactor

#21 [feature] 계정 관련 페이지 (로그인/로그아웃/회원가입) 기본 마크업 구조 작성
  client/src/Components/Auth/Login.ts
  client/src/Components/Auth/Logout.ts
  client/src/Components/Auth/Register.ts
  client/src/Components/Auth/index.ts
  client/src/Components/Auth/styles.scss
  client/src/Components/Home/index.ts
  client/src/Components/Shared/TextInput/index.ts
  client/src/Components/Shared/TextInput/styles.scss
  client/src/main.ts
Labels: enhancement

#24 [refactor] ChatListItem / ChatBubble 컴포넌트 단일 템플릿 원칙 준수를 위한 개선
  client/src/Components/ChatDetail/index.ts
  client/src/Components/ChatList/index.ts
  client/src/Components/Shared/ChatBubble/index.ts
  client/src/Components/Shared/ChatListItem/index.ts
Labels: refactor

#25 [feature] 위치설정 페이지 기본 마크업 구조 및 컴포넌트 작성
  client/assets/add-mint.svg
  client/assets/close-mint.svg
  client/src/Components/Home/index.ts
  client/src/Components/Location/index.ts
  client/src/Components/Location/styles.scss
  client/src/Components/Shared/LocationButton/index.ts
  client/src/Components/Shared/LocationButton/styles.scss
  client/src/main.ts
Labels: enhancement

#29 [bugfix] IconButton path props 를 name props 로 변경
  client/src/Components/SalesProductDetail/index.ts
  client/src/Components/Shared/Status/index.ts
Labels: bug

#35 [fefactor] dropdown 클래스 컴포넌트 렌더링 로직 변경
  client/src/Components/Home/index.ts
  client/src/Components/SalesProductDetail/index.ts
  client/src/Components/Shared/Dropdown/index.ts
  client/src/Components/Shared/Dropdown/styles.scss
  client/src/Components/Shared/Header/styles.scss
  client/src/Components/Shared/Status/index.ts
  client/src/core/Component.ts
  client/src/lib/router.ts
Labels: refactor

#37 [refactor] 기획서 디자인 요구사항 미구현 부분 일부 적용
  client/assets/end-off.svg
  client/assets/end-on.svg
  client/assets/logout.svg
  client/src/Components/Auth/styles.scss
  client/src/Components/ChatDetail/index.ts
  client/src/Components/ChatDetail/styles.scss
  client/src/Components/ChatList/index.ts
  client/src/Components/SalesProductDetail/index.ts
  client/src/Components/SalesProductDetail/styles.scss
  client/src/Components/Shared/ChatBar/index.ts
  client/src/Components/Shared/ChatBar/styles.scss
  client/src/Components/Shared/ChatBubble/styles.scss
  client/src/Components/Shared/ChatListItem/index.ts
  client/src/Components/Shared/ChatListItem/styles.scss
  client/src/Components/Shared/ImgBox/styles.scss
  client/src/Components/Shared/InfoProduct/index.ts
  client/src/Components/Shared/InfoProduct/styles.scss
  client/src/Components/Shared/InfoSaler/index.ts
  client/src/Components/Shared/InputPopup/indext.ts
  client/src/Components/Shared/InputPopup/styles.scss
  client/src/Components/Shared/ProductBar/styles.scss
  client/src/Components/Shared/Status/index.ts
  client/src/Components/Shared/Status/styles.scss
  client/src/Components/Shared/TextInput/index.ts
  client/src/Components/Shared/TextInput/styles.scss
  client/src/scss/index.scss
Labels: refactor

#39 [refactor] 상품 상세페이지 및 채팅 라우팅 재설정
  client/src/Components/ChatDetail/index.ts
  client/src/Components/ChatList/index.ts
  client/src/Components/SalesProductDetail/index.ts
  client/src/Components/Shared/InfoSaler/index.ts
  client/src/Components/Shared/InfoSaler/styles.scss
  client/src/Components/Shared/InputPopup/indext.ts
  client/src/Components/Shared/ProductBar/index.ts
  client/src/Components/Shared/Status/index.ts
  client/src/Components/Shared/Status/styles.scss
Labels: refactor

#43 [fix] 중복 router 모두 mounted 에서 관리하도록 수정
  client/src/Components/ChatList/index.ts
  client/src/Components/Location/index.ts
  client/src/Components/Shared/ChatListItem/index.ts
Labels: bug

#47 [refactor] 동적 라우팅 처리 로직 추가
  client/src/Components/Shared/CategoryListItem/index.ts
  client/src/Components/Shared/ChatListItem/index.ts
  client/src/lib/router.ts
Labels: refactor

#50 [refactor] router 클래스 불필요한 부분 개선
  client/src/lib/router.ts
Labels: refactor

#51 [feature] 버그픽스 및 글쓰기 페이지 추가 구현
  client/src/Components/NewPost/index.ts
  client/src/Components/NewPost/styles.scss
  client/src/Components/Shared/Button/index.ts
  client/src/Components/Shared/Button/styles.scss
  client/src/Components/Shared/CategoryListItem/index.ts
  client/src/Components/Shared/Header/styles.scss
  client/src/Components/Shared/ImgButton/index.ts
Labels: bug, enhancement

#52 [feature] 이미지 슬라이더 작성
  client/src/Components/SalesProductDetail/index.ts
  client/src/Components/Shared/ImgNavigation.ts
  client/src/Components/Shared/ImgNavigation/NavItem.ts
  client/src/Components/Shared/ImgNavigation/index.ts
  client/src/Components/Shared/ImgNavigation/styles.scss
  client/src/lib/router.ts
Labels: enhancement

#49 [refactor] 로그인/로그아웃/회원가입 페이지 렌더 방식 변경
  client/src/Components/Auth/Login.ts
  client/src/Components/Auth/Logout.ts
  client/src/Components/Auth/Register.ts
  client/src/Components/Auth/index.ts
  client/src/Components/Auth/styles.scss
  client/src/Components/Shared/Button/styles.scss
  client/src/index.html
  client/src/main.ts
  client/src/scss/index.scss
Labels: refactor

#88 [bugfix] 카테고리 비 로그인 유저 관련 오류 처리
  client/src/Components/CategoryResult/index.ts
  client/src/Components/Home/index.ts
  client/src/Components/Shared/CategoryListItem/index.ts
  client/src/Components/Shared/InfoProduct/index.ts
  client/src/Components/Shared/ProductBar/index.ts
  client/src/lib/util.ts
  server/queries/post.ts
Labels: bug

#89 [bugfix] slider 이미지가 1장일 때는 carousel 기능 제거
  client/src/Components/Shared/ImgBox/styles.scss
  client/src/Components/Shared/ImgNavigation/index.ts
  client/src/Components/Shared/ImgNavigation/styles.scss
  client/src/lib/router.ts
Labels: bug

#90 [fix] 채팅 관련 버그 해결
  client/src/Components/ChatDetail/index.ts
  client/src/Components/ChatList/index.ts
  client/src/Components/Menu/index.ts
  client/src/Components/Shared/ChatListItem/index.ts
  server/controllers/ChatController.ts
  server/queries/chat.ts
  server/routes/chat.ts
  server/services/ChatService.ts
  server/socket.ts
Labels: bug
